### PR TITLE
Testing AerTV Compatability

### PR DESCRIPTION
**Pull request by rlaphoenix**

### CODE REVIEW

**Comment by mathsgrinds** [comment]
Great, however it sense there is conflics, I think because I made changes since you have made changes but I could add the new AerTV function in and give the user a username and password entry in the settings

**Comment by rlaphoenix** [comment]
o.o o shit just realized something 1 sec

**Comment by mathsgrinds** [comment]
go on

**Comment by rlaphoenix** [comment]
It had something in it that shouldnt be in it at all lol

**Pull request closed without merging**
