### PR TITLE
v2.1.6 - Tons of changes.

### PR DESCRIPTION
**Pull request by rlaphoenix**
Ok so in this it is 100% up to date with your repo I can assure you that, When I finished coding it up - I re-checked your repo and there was still no changes. So its 100% up to date with yours.

Changes:
- Tbh too many to mention here, Ill mention ones I can remember;
- Many Small Code Changes (AGAIN) - YOU WILL NOT NOTICE THEM!
- Guide Re-Fixed (Your "Guide Fixed" commit didnt actually fix it - Atleast for me)
- AerTV fixes to make sure it works;
- Moved the j = login() for it to actually be useful; Also renamed it so it doesnt conflict with AerTV's j = html bit;
- Guide Improvements;
- RTE One +1 Added (AerTV), AerTV Choice for TG4 Added, RTE Two AerTV link changed from "rte-two" to "rte-two" as it seems free users have access to it. RTE News Now AerTV Choice Added;
- Changed Settings.xml heavilly, Instead of the "TV3/3e Stream Choice" thing, Its now set to "Preffered Stream Choice" with options "Official Site, AerTV.ie", If its set to Official Site it will be used wherever it can be used, Otherwise AerTV links will get parsed.

Theres tons more changes ones you arent going to notice.
Please can you just copy and paste into the Repo so we can start using Merge again?
I assure you it works 100% and is up to date with your repo.

P.S: You should give me "Write Access" so I dont need to use these stupid Pull Requests thing. I could then edit directly to your repo. Of course theres a Trust Issue but its safe :P If I fuckup your repo you can just go back to the last commit # before I screw up your repo (Not that I would ofc)

### CODE REVIEW

**Comment by mathsgrinds** [comment]
Okay, I think that is all in order. Two small errors needed to be fixed (rte2 not playing) and guide doesn’t work when station is closed (so added in a try-except dealey).

Thanks bud.

Stephen Easley-Walsh

 https://www.mathsgrinds.ie/ https://www.MathsGrinds.ie

0851263404

****\* Email confidentiality notice *****

This message is private and confidential. If you have received this message in error, please notify me and remove it from your system.

**Comment by mathsgrinds** [comment]
Hmmmm, it’s now a work of art, me gusta.

Stephen Easley-Walsh

 https://www.mathsgrinds.ie/ https://www.MathsGrinds.ie

0851263404

****\* Email confidentiality notice *****

This message is private and confidential. If you have received this message in error, please notify me and remove it from your system.

**Comment by rlaphoenix** [comment]
Is this Pull Request ready to be closed?

**Comment by rlaphoenix** [comment]
Nope its not ready to be closed - I dont think you copied all of the files, Remember you need to copy the resources folder (RTE +1 logo and settings) icon.png etc (I modified icon.png to the style you had but made it looks better, Flag colors are a good idea but the Ireland Map thing is just stupid imo)

Copy and paste EVERYTHING from my repo.

**Comment by rlaphoenix** [comment]
Also RTE Two was working perfectly fine for me - Not sure where you had an error maybe it was the free account? But I made a fresh new account and I got a stream link using `AerTV('rte-two-hd')` perfectly fine.

**Comment by mathsgrinds** [comment]
Okay, I've made all the changes, and I removed the version numbering. So I think it is all good now.

**Pull request closed without merging**
